server:
  port: 8099

spring:
  application:
    name: kotlin-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin_spring
    driver-class-name: org.postgresql.Driver
    username:
    password:
  flyway:
    clean-disabled: false
    enabled: false
    fail-on-missing-locations: true
    validate-migration-naming: true

app:
  resetDbSchemas: true
